### PR TITLE
Fix navbar links active state

### LINKED ISSUE #141: Side-bar does not show correct active links when we try to open a url directly.
When we try to go to a link directly by entering it into navbar, rather than navigating to it the active link in the side navbar is not correct.

Also by default, the navbar does not show correct active link, the default active link is `Discover` but the sidebar show `My Demos` active by default.

**Step to reproduce**
Enter a URL in browser search bar other than home, like `http://localhost:8000/initialsetup` or `http://localhost:8000/ngh/user` and see that the sidebar does not have the correct active option.

image

### PR DESCRIPTION
**Pull request by fristonio**
- Fixes #141
- Fix navigation bar links to show correct active state.
- Fix default active link in the navbar.

### CODE REVIEW

**Comment by AvaisP** [comment]
Please fix the conflicts

**Comment by fristonio** [comment]
@AvaisP I have fixed the conflicts with master, please have a look :)

**Comment by AvaisP** [comment]
Will chec this out and merge it tomorrow

**Comment by uttu357** [comment]
@fristonio Please resolve the conflicts.

**Comment by fristonio** [comment]
@uttu357 I have resolved all the conflicts. Can you have a look.

**Pull request merged**
