### PR TITLE
Improve installation instructions

### PR DESCRIPTION
**Pull request by itaisteinherz**
## Description

This improves the documentation for getting started with Origami.

## Reviewers

@RishabhJain2018 @erikaaatan

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other

### CODE REVIEW

**Comment by erikaaatan** [comment]
Hey @itaisteinherz , each task can have multiple instances so more than one person can claim it at once. Coincidentally, a bunch of people took up this task recently, which is why this happened. Also, to keep everything in one place the changes should just be made to the README file. Any thoughts @RishabhJain2018 ?

**Comment by itaisteinherz** [comment]
@erikaaatan Done.
Since there are 5 PRs open with the same purpose, which PR are you going to merge?

**Comment by erikaaatan** [comment]
@itaisteinherz That's still undecided since there are still a few instances of this task left, iirc. Ideally we would take the important/unique parts of everyone's contributions so that the README can be as descriptive as possible without repeating information.

**Comment by itaisteinherz** [comment]
@erikaaatan @RishabhJain2018 Any updates on this?

**Comment by itaisteinherz** [comment]
@erikaaatan Shall I close this now that #263 has been merged?

**Comment by itaisteinherz** [comment]
I'm going to close this now, as it seems like this isn't going to get merged.

**Pull request closed without merging**
